services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./results:/app/hse_tools/results
      - ./hse_nspd_settlements.py:/app/hse_tools/hse_nspd_settlements.py